// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://hngssnisxasumvxoands.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhuZ3NzbmlzeGFzdW12eG9hbmRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMzOTk4NTUsImV4cCI6MjA0ODk3NTg1NX0.7POsoW20omR5l4xh_OstAVMfJDcPn65YNtZEAI1dme0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);